### ISSUE TITLE
Alarms and timers

### ISSUE THREAD

**Issue by Pajn** [endoplasmic/google-assistant#10]
The 0.0.2 release does support alarms and timers https://developers.google.com/assistant/sdk/release-notes

Can this library support these? With the mic and speaker example I can set these but they obviously never goes of as the program ends.

**Comment by endoplasmic** [comment]
I'm not sure where in the python code those hooks are. The gRPC doesn't seem to be exposing that, so the python code must have some extra sugar to handle it. Also, I can't for the life of me seem to find the python stuff that handles the timers at all.

If you point me in the right direction, I could probably figure out how to port it over to this :)

**Comment by Pajn** [comment]
I know even less than you so no pointing right now at least, I only saw the changelog. But I'll let you know if I find anything out.

**Comment by endoplasmic** [comment]
Right on, and I'll keep an eye out for any source code that lets me do all that kind of stuff. I think right now they are using python with .so files. It's a bit over my head, but maybe that's the angle to take.

**Comment by Pajn** [comment]
You are right, it seems not to be possble right now. The whole thing seems to be implemented in a C library without source code that is only compiled for arm7hf. Here https://developers.google.com/assistant/sdk/reference/library/python/ is the Python class that dispatches alarm events but the only thing the Python code does is bind to an .so.

Depending on how this issue is resolved https://github.com/google/aiyprojects-raspbian/issues/79 it may make it possible (if alarms are implemented in grpc instead). Otherwise if this issue is resolved https://github.com/googlesamples/assistant-sdk-python/issues/71 we could at least use that library as well.

**Comment by endoplasmic** [comment]
I'm gonna close this now since the gRPC service still doesn't allow for timers and alarms in v1alpha2 :(
